name: test
on: push
jobs:
        test:
                runs-on: ubuntu-22.04
                container: tsubokuraryosuke/ubuntu22.04-ros2:latest
                step:
                        uses: actions/checkout@v2
                        name: build and test
                        run: |
                                rsync -av ./ /root/src/mypkg/
                                cd /root/src
                                rosdep update
                                rosdep install -i --from-path src --rosdistro humble -y
                                bash -xv ./src/mypkg/test/test.bash/root

